platform :ios ,'7.0'
pod 'JSONKit'
pod 'ASIHTTPRequest'
pod 'SIAlertView'
pod 'UIColor-Utilities'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'PopoverView'
pod 'ATMHud'
pod 'FMDB'
pod 'iCarousel'
pod 'pop'
pod 'UIImage-ResizeMagick'